### ISSUE TITLE
Mod cannot initialize at all

### ISSUE THREAD

**Issue by emipa606** [maarxx/SmarterScheduling#97]
Tried adding the mod to my save but noticed no difference. 
Seems the map-component fails in some way on load.
Log if it helps:
https://gist.github.com/HugsLibRecordKeeper/309daf53ba08dc053c3d869dbefd4301

**Comment by maarxx** [comment]
You can push the bottom-most button to enable debug logging, where it should output (at least) one line per colonist, per cycle (every 200 ticks or so).

If it is working for _at least some_ of the colonists, you might get a listing of names, but it stops early (not considering certain colonists). You might be able to guess which colonist, due to a particular weird state or mod, and I can look into that.

If it isn't working for any colonists at all, I'm not sure next steps. If you could resave with a shorter mod list that still replicates the issue, and send that save/modlist, I can look into that too.

**Comment by emipa606** [comment]
I had that option on, the mod does not seem to be able to initiate at all. Probably some other mod that causes issues with it, have one that adds a timeslot-type (Dinner) for example.
Wont be testing more since I only tested the mod to see what it did.

**Comment by maarxx** [comment]
Cleanup, closing, insufficient information to identify any issue.
